name: CI
on:
    push:
        branches: [ master]
jobs:
    build-and-test:
        runs-on: self-hosted
        steps: 
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install dependencies
              run: npm i
            - name: Build
              run: npm run build
            - name: Test
              run: npm test 
        